version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge

volumes:
  postgres:
  mysql: